### ISSUE TITLE
Throwing from a setTimeout is very confusing

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/next-js-setup#128]
I imagine there's good reasoning behind it, but [this disembodied throw](https://github.com/Financial-Times/next-js-setup/blob/c5522430ac4afbea82669976b46c6b54391434da/src/js-setup.js#L13-L17) just cause a very long and confusing debugging session for me:

```js
class JsSetup {

	_throw (err) {
		setTimeout(function () {
			throw err;
		}, 0);
	}
```

It seems to cause things to fail at different points each time:

```js
require('next-js-setup').bootstrap(({flags}) => {
  thing1();
  thing2();
  thing3();
  thing4();
});
```

I was getting some very weird race conditions happening when I had the debugger open. Sometimes it would get as far as `thing1()`, sometimes `thing3()`, etc...

I don't know why a throw from a setTimeout should break anything, but it seems to in this case. And the fact that it happens at an indeterminate point in the future (after *x* other operations have already started) makes it very, very confusing if you're pausing on exceptions in the debugger... Things seem to break in different ways every time you run the code.

Can we get rid of this? I'm guessing the setTimeout throw is an attempt to make sure unhandled rejections don't go unnoticed. I'm not sure this kind of hack is necessary any more (Chrome prints out unhandled rejections in the console now, not sure about other browsers). But if it is still necessary for some browsers, could we just do `.catch(err => console.error(err.stack))` instead?

**Comment by wheresrhys** [comment]
I agree it's a debugging pain. I think it's there to make sure errors get in to sentry, but it predates o-errors so now we have a nice interface provided for that we can probably get rid of it. Although then we may end up having to branch between prod and dev, but as it'd only be at a point when an unexpected error has already happened then that's not such a dangerous thing

**Comment by callumlocke** [comment]
Thanks Rhys!
